### ISSUE TITLE
socket_can_bridge.launch.xml is not working if group tag is added

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/ros2_socketcan#8]
Normally, `socket_can_bridge.launch.xml` works correctly.

```xml
$ ros2 launch ros2_socketcan socket_can_bridge.launch.xml interface:=vcan0
[INFO] [launch]: All log files can be found below /home/kenji/.ros/log/2021-03-28-15-45-41-152424-desktop-1257792
[INFO] [launch]: Default logging verbosity is set to INFO
1616913941.225444 [19]       ros2: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[INFO] [socket_can_receiver_node_exe-1]: process started with pid [1257803]
[INFO] [socket_can_sender_node_exe-2]: process started with pid [1257805]
[socket_can_receiver_node_exe-1] 1616913941.245093 [19] socket_can: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[socket_can_sender_node_exe-2] 1616913941.245764 [19] socket_can: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[socket_can_receiver_node_exe-1] [INFO 1616913941.249226146] [socket_can_receiver]: interface: vcan0
[socket_can_receiver_node_exe-1] [INFO 1616913941.249265876] [socket_can_receiver]: interval(s): 0.010000
[socket_can_sender_node_exe-2] [INFO 1616913941.249974288] [socket_can_sender]: interface: vcan0
[socket_can_sender_node_exe-2] [INFO 1616913941.250025899] [socket_can_sender]: timeout(s): 0.010000
```

Or this is okay.

```xml
// test.launch.xml
<launch>
  <include file="$(find-pkg-share ros2_socketcan)/launch/socket_can_bridge.launch.xml">
    <arg name="interface" value="vcan0" />
  </include>
</launch>
```

```sh
$ ros2 launch ./test.launch.xml
(Same result)
```

However, if `group` tag is added, it doesn't work. `auto_configure` and `auto_activate` couldn't be resolved.

```xml
// test.launch.xml
<launch>
  <group>
    <include file="$(find-pkg-share ros2_socketcan)/launch/socket_can_bridge.launch.xml">
      <arg name="interface" value="vcan0" />
    </include>
  </group>
</launch>
```

```sh
$ ros2 launch ./test.launch.xml 
[INFO] [launch]: All log files can be found below /home/kenji/.ros/log/2021-03-28-15-46-32-602952-desktop-1257993
[INFO] [launch]: Default logging verbosity is set to INFO
1616913992.678658 [19]       ros2: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[INFO] [socket_can_receiver_node_exe-1]: process started with pid [1258004]
[INFO] [socket_can_sender_node_exe-2]: process started with pid [1258006]
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=SubstitutionFailure("launch configuration 'auto_configure' does not exist")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 106, in visit
    if self.__condition is None or self.__condition.evaluate(context):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/condition.py", line 44, in evaluate
    return self._predicate(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/conditions/if_condition.py", line 43, in _predicate_func
    return evaluate_condition_expression(context, self.__predicate_expression)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/conditions/evaluate_condition_expression_impl.py", line 41, in evaluate_condition_expression
    expanded_expression = perform_substitutions(context, expression)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 184, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/substitutions/launch_configuration.py", line 98, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: launch configuration 'auto_configure' does not exist
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=SubstitutionFailure("launch configuration 'auto_configure' does not exist")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 106, in visit
    if self.__condition is None or self.__condition.evaluate(context):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/condition.py", line 44, in evaluate
    return self._predicate(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/conditions/if_condition.py", line 43, in _predicate_func
    return evaluate_condition_expression(context, self.__predicate_expression)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/conditions/evaluate_condition_expression_impl.py", line 41, in evaluate_condition_expression
    expanded_expression = perform_substitutions(context, expression)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 184, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/substitutions/launch_configuration.py", line 98, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: launch configuration 'auto_configure' does not exist
[socket_can_receiver_node_exe-1] 1616913992.698730 [19] socket_can: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[socket_can_sender_node_exe-2] 1616913992.699225 [19] socket_can: using network interface enp8s0 (udp/172.16.81.153) selected arbitrarily from: enp8s0, br-51dac8a7becc, docker0
[socket_can_receiver_node_exe-1] [INFO 1616913992.701642017] [socket_can_receiver]: interface: vcan0
[socket_can_receiver_node_exe-1] [INFO 1616913992.701682377] [socket_can_receiver]: interval(s): 0.010000
[socket_can_sender_node_exe-2] [INFO 1616913992.704002656] [socket_can_sender]: interface: vcan0
[socket_can_sender_node_exe-2] [INFO 1616913992.704059466] [socket_can_sender]: timeout(s): 0.010000
```

**Comment by kenji-miyake** [comment]
Just removing `auto_configure` and `auto_activate` can fix this problem, but I'll try to investigate in a bit more detail.

**Comment by kenji-miyake** [comment]
Probably related? https://github.com/ros2/launch_ros/issues/114
